# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core



trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'



steps:
- task: SonarCloudPrepare@4
  inputs:
      SonarQube: 'Sonarcloud'
      organization: 'devops-anil-1'
      scannerMode: 'dotnet'
      projectKey: 'devops-anil_Dotnetcorewebapi'
      projectName: 'Dotnetcorewebapi'
      
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarCloudAnalyze@4
  inputs:
      jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@4
  inputs:
    pollingTimeoutSec: '240'





# - task: AdvancedSecurity-Codeql-Init@1
#   inputs:
#     languages: 'csharp'
#     querysuite: 'code-scanning'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'build'
#     projects: '**/*Dotnetcorewebapi/*.csproj'

# - task: AdvancedSecurity-Codeql-Analyze@1
#   inputs:
#     WaitForProcessing: true

# - task: AdvancedSecurity-Publish@1
#   inputs:
#     SarifsInputDirectory: '$(Build.SolutionDirectory)/.gdn/'
#     EnableRecursiveScanning: true
#     WaitForProcessing: true

  
- script: |
    echo "Listing files..."
    ls -R
  displayName: 'Show folder structure'

- task: Docker@2
  inputs:
      containerRegistry: 'Docker-Dotnetcorewebapi'
      repository: 'anilgaikwad123/dotnetcorewebapi'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/Dotnetcorewebapi/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/Dotnetcorewebapi'