# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core



trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: AdvancedSecurity-Codeql-Init@1
  inputs:
    languages: 'csharp'
    querysuite: 'code-scanning'

- task: AdvancedSecurity-Codeql-Analyze@1
  inputs:
    WaitForProcessing: true

  
- script: |
    echo "Listing files..."
    ls -R
  displayName: 'Show folder structure'

- task: Docker@2
  inputs:
      containerRegistry: 'Docker-Dotnetcorewebapi'
      repository: 'anilgaikwad123/dotnetcorewebapi'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/Dotnetcorewebapi/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/Dotnetcorewebapi'